[build]
  command = "pnpm install && pnpm build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/next"

[dev]
  command = "next dev"
  port = 3000
  targetPort = 3000
